services:
  frontend:
    image: ${ECR_FRONTEND_IMAGE}
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: https://bestziyu.xyz/api  # Backend URL in prod env (use domain name)
    networks:
      - my_network

  backend:
    image: ${ECR_BACKEND_IMAGE}
    container_name: backend
    ports:
      - "8800:8800"
    environment:
      DB_HOST: ${DB_HOST}  # RDS endpoint
      DB_PORT: 3306
      DB_USER: ${DB_USER}  # RDS master user
      DB_PASSWORD: ${DB_PASSWORD}       # RDS password
      DB_NAME: ${DB_NAME}               # RDS DB name
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - my_network

networks:
  my_network: